import type { CellData} from './EditorTypes';
import { GRID_W, GRID_H, ENTITY_TYPES, PICKUP_TYPES } from './EditorTypes';
import { ENEMY_MAX_HEALTH } from '@/game/types';
import type { EnemyType } from '@/game/types';
import type { LevelLightingData } from '@/shared/storage/StorageHelpers';

function getCell(grid: CellData[][], x: number, z: number): CellData {
  if (x < 0 || x >= GRID_W || z < 0 || z >= GRID_H) return { type: 'wall' };
  return grid[z]?.[x] ?? { type: 'wall' };
}

export interface ExportedLevelData {
  walls: Array<{ x: number; z: number; w: number; d: number; isDoor: boolean; isHalfWall?: boolean; color?: string }>;
  enemies: Array<{ id: number; x: number; z: number; type: string }>;
  pickups: Array<{ id: number; x: number; z: number; type: string }>;
  barrels: Array<{ id: number; x: number; z: number }>;
  specialFloors: Array<{ x: number; z: number; type: 'lava' | 'slime' }>;
  playerStart: [number, number];
  musicTrack?: string | undefined;
  lighting?: LevelLightingData | undefined;
}

// Export grid-to-level-data converter for use by the game and export
export function gridToLevelData(
  grid: CellData[][],
  playerPos: [number, number] | null,
  musicTrack?: string,
  lighting?: LevelLightingData,
): ExportedLevelData {
  const visited = new Set<string>();
  const walls: Array<{ x: number; z: number; w: number; d: number; isDoor: boolean; isHalfWall?: boolean; color?: string }> = [];

  for (let z = 0; z < GRID_H; z++) {
    for (let x = 0; x < GRID_W; x++) {
      const key = `${x},${z}`;
      if (visited.has(key)) continue;
      const cell = getCell(grid, x, z);
      if (cell.type !== 'wall' && cell.type !== 'door' && cell.type !== 'halfwall') continue;

      let maxX = x;
      while (maxX + 1 < GRID_W && getCell(grid, maxX + 1, z).type === cell.type) maxX++;

      let maxZ = z;
      let canExtend = true;
      while (canExtend && maxZ + 1 < GRID_H) {
        for (let cx = x; cx <= maxX; cx++) {
          if (getCell(grid, cx, maxZ + 1).type !== cell.type) {
            canExtend = false;
            break;
          }
        }
        if (canExtend) maxZ++;
      }

      const w = maxX - x + 1;
      const d = maxZ - z + 1;
      const isHalfWall = cell.type === 'halfwall';
      walls.push({
        x,
        z,
        w,
        d,
        isDoor: cell.type === 'door',
        isHalfWall,
        color: cell.type === 'door' ? '0xcc0000' : isHalfWall ? '0x6e563a' : '0x8b7355'
      });

      for (let vz = z; vz <= maxZ; vz++) {
        for (let vx = x; vx <= maxX; vx++) {
          visited.add(`${vx},${vz}`);
        }
      }
    }
  }

  const enemies: Array<{ id: number; x: number; z: number; type: string }> = [];
  const pickups: Array<{ id: number; x: number; z: number; type: string }> = [];
  const barrels: Array<{ id: number; x: number; z: number }> = [];
  const specialFloors: Array<{ x: number; z: number; type: 'lava' | 'slime' }> = [];
  let enemyId = 0;
  let pickupId = 1;
  let barrelId = 0;

  for (let z = 0; z < GRID_H; z++) {
    for (let x = 0; x < GRID_W; x++) {
      const cell = getCell(grid, x, z);
      if ((ENTITY_TYPES as readonly string[]).includes(cell.type)) {
        enemies.push({ id: enemyId++, x, z, type: cell.type });
      } else if ((PICKUP_TYPES as readonly string[]).includes(cell.type)) {
        pickups.push({ id: pickupId++, x, z, type: cell.type });
      } else if (cell.type === 'barrel') {
        barrels.push({ id: barrelId++, x, z });
      } else if (cell.type === 'lava' || cell.type === 'slime') {
        specialFloors.push({ x, z, type: cell.type });
      }
    }
  }

  return {
    walls,
    enemies,
    pickups,
    barrels,
    specialFloors,
    playerStart: playerPos ? [playerPos[0], playerPos[1]] as [number, number] : [2, 2] as [number, number],
    musicTrack,
    lighting,
  };
}

export function buildExportCode(
  grid: CellData[][],
  playerPos: [number, number] | null,
  lighting?: LevelLightingData
): string {
  const levelData = gridToLevelData(grid, playerPos, undefined, lighting);
  
  let code = `// Generated by Doom Level Editor\n`;
  code += `// JSON level data (copy to save as custom map):\n`;
  code += `const LEVEL_DATA = ${JSON.stringify(levelData, null, 2)};\n\n`;

  code += `const WALL_DATA = [\n`;
  for (const w of levelData.walls) {
    const yVal = w.isHalfWall ? 0.5 : 2;
    const hVal = w.isHalfWall ? 1.0 : 4;
    code += `  { x: ${w.x}, y: ${yVal}, z: ${w.z}, w: ${w.w}, h: ${hVal}, d: ${w.d}, color: ${w.color}${w.isHalfWall ? ', isHalfWall: true' : ''} },\n`;
  }
  code += `];\n\n`;

  code += `// Enemies\n`;
  for (const e of levelData.enemies) {
    const hp = ENEMY_MAX_HEALTH[e.type as EnemyType] ?? 35;
    code += `{ id: ${e.id}, position: [${e.x}, 0, ${e.z}], type: "${e.type}", health: ${hp}, maxHealth: ${hp}, alive: true, lastAttack: 0, hitFlash: 0, rotation: Math.PI, stuckCounter: 0, lastPosition: [${e.x}, 0, ${e.z}] as [number, number, number], hasAlerted: false },\n`;
  }
  code += `\n`;

  code += `// Pickups\n`;
  for (const p of levelData.pickups) {
    code += `{ id: ${p.id}, position: [${p.x}, 0.3, ${p.z}], type: "${p.type}", active: true },\n`;
  }
  code += `\n`;

  code += `// Barrels\n`;
  for (const b of levelData.barrels) {
    code += `{ id: ${b.id}, position: [${b.x}, 0.5, ${b.z}], radius: 0.4, health: 20, maxHealth: 20, alive: true, explosionTimer: 0 },\n`;
  }
  code += `\n`;

  code += `// Special Floors\n`;
  for (const f of levelData.specialFloors) {
    code += `{ x: ${f.x}, z: ${f.z}, type: "${f.type}" },\n`;
  }
  code += `\n`;

  if (playerPos) {
    code += `// Player start\n`;
    code += `position: new THREE.Vector3(${playerPos[0]}, 1.7, ${playerPos[1]}),\n`;
  }

  return code;
}
